[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  TRANSPORT_MODE = "http"
  NODE_ENV = "production"

[functions]
  directory = "dist"

[functions."*"]
  timeout = 300

[[redirects]]
  from = "/health"
  to = "/.netlify/functions/index"
  status = 200

[[redirects]]
  from = "/sse"
  to = "/.netlify/functions/index"
  status = 200

[[redirects]]
  from = "/messages"
  to = "/.netlify/functions/index"
  status = 200

[[redirects]]
  from = "/analyze/*"
  to = "/.netlify/functions/index"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/index"
  status = 200
